#!venv/bin/python -u
import os
from urllib.parse import urlsplit, urlunsplit

import aiohttp
import uvicorn
from multidict import CIMultiDict
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.requests import Request
from starlette.responses import Response
from starlette.routing import Route

url_roots = {"app-prod": "https://app.agicap.com",
             "app-preprod": "https://preprod.agicap.cloud",
             "app-dev": "https://dev.agicap.cloud"}
session = None


async def get(request: Request) -> Response:
    global session
    if not session:
        session = aiohttp.ClientSession()
    # Chop scheme + netloc from URL
    url = urlunsplit(urlsplit(str(request.url))._replace(scheme='', netloc=''))
    url_root = url_roots[url.split("/")[1]]
    url = url_root + url.replace(url.split("/")[1], "")[1:]

    method = request.method
    hdr = request.headers
    hdr = CIMultiDict((k, v) for k, v in hdr.items() if k != 'host')

    if method == 'GET':
        func = session.get(url, headers=hdr)
    elif method == 'POST':
        func = session.post(url, headers=hdr, data=(await request.body()))
    elif method == 'PUT':
        func = session.put(url, headers=hdr, data=(await request.body()))
    elif method == 'PATCH':
        func = session.patch(url, headers=hdr, data=(await request.body()))
    elif method == 'DELETE':
        func = session.delete(url, headers=hdr)
    elif method == 'HEAD':
        func = session.head(url, headers=hdr)
    else:
        return Response(f'Unsupported HTML method "{method}"', 501)

    async with func as response:
        # Some servers have blank chars on end of key values which
        # Starlette does not like
        hdr = CIMultiDict((k, v.strip())
                          for k, v in response.headers.items() if k.lower() != 'content-encoding')
        hdr["Access-Control-Allow-Origin"] = "*"
        # hdr["Content-Type"] = "application/json"

        return Response((await response.read()), response.status, hdr)


# Set routes and middleware
routes = [Route('/{path:path}', get, methods=['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD'])]
middleware = [Middleware(CORSMiddleware, allow_origins=['*'],
                         allow_methods=['*'], allow_headers=['*'])]

# Create the app instance
app = Starlette(routes=routes, middleware=middleware)
uvicorn.run(app, host="0.0.0.0", port=int(os.getenv("PORT", "8080")), server_header=False, date_header=False,
            log_level="debug")
